# Deep Learning: AI / ML
- RNN (Recurrent Neural Networks) Algorithm.
- RNN for Sentimental Analysis for IMDP Data.

In [1]:
import pandas as pd
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

## Load Data:

In [2]:
df = pd.read_csv("IMDB Dataset.csv")

In [3]:
df.shape

(50000, 2)

In [4]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

## Checking Null & dublicates Values:

In [5]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [6]:
df.drop_duplicates(inplace = True)

In [7]:
df.shape

(49582, 2)

## Data Text Pre-Processing:

### 1. Converting to lowercase:

In [8]:
df["review"] = df["review"].str.lower()

### 2. Removing the URLs:

In [9]:
# Example with Regex:
sample_text = "abc is the world, abc" # abc -> xyz
new_text = re.sub("abc", "xyz", sample_text)

In [10]:
sample_text

'abc is the world, abc'

In [11]:
new_text

'xyz is the world, xyz'

### Data Text Pre-Processing using Regex:

In [12]:
def remove_url(text):
    text = re.sub(r"http\S+" , "", text) # (pattern, replacement, string)
    return text

df["review"] = df["review"].apply(remove_url)

### 3. Removing Punctuations:

In [13]:
def remove_punctuations(text):
    text = re.sub(r"[^A-Za-z0-9\s]" , "", text) # A-Z a-z 0-9 \s
    return text

df["review"] = df["review"].apply(remove_punctuations)

In [14]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production br br the filmin...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

### 4. Removing HTML Tags:

In [15]:
def remove_html(text):
    text = re.sub(r"<.*?>" , "", text) # A-Z a-z 0-9 \s
    return text

df["review"] = df["review"].apply(remove_html)

### 5. Removing the StopWords using NLTK:

In [16]:
nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\satin\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\satin\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\satin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [17]:
# Example Code:
sample_text2 = "I like coding in Python!"
tokens_example = word_tokenize(sample_text2)

In [18]:
tokens_example

['I', 'like', 'coding', 'in', 'Python', '!']

In [19]:
def remove_stopwords(text):
    tokens = word_tokenize(text)
    stop_words = stopwords.words("english")

    for word in tokens:
        if word in stop_words:
            text = text.replace(word, "")

    return text

df["review"] = df["review"].apply(remove_stopwords)

In [20]:
df.head()

                                              review sentiment
0  e    revewers  nted   wtchg  1 oz epode ll  ho...  positive
1   wderful ltle producti br br  filming techniqu...  positive
2   thought ths   wderful wy  spend tme   o hot s...  positive
3  bsclly res  fmly   lttle boy jke thks res  zom...  negative
4  petter mtte love   time  mey   vully stunng fi...  positive