# AI / ML: Deep Learning – GenAI - Transformers
- Text Summarizer App (HuggingFace Transformer)

In [22]:
import pandas as pd
from transformers import T5Tokenizer, Trainer, TrainingArguments, T5ForConditionalGeneration
import re

## Reading Data:

In [9]:
train_data = pd.read_csv("samsum-train.csv")
val_data = pd.read_csv("samsum-validation.csv")

In [11]:
train_data.head()

,id,dialogue,summary
0,13818513,Amanda: I baked cookies. Do you want some?\r\...,Amanda baked cookies and will bring Jerry some...
1,13728867,Olivia: Who are you voting for in this electio...,Olivia and Olivier are voting for liberals in ...
2,13681000,"Tim: Hi, what's up?\r\nKim: Bad mood tbh, I wa...",Kim may try the pomodoro technique recommended...
3,13730747,"Edward: Rachel, I think I'm in ove with Bella....",Edward thinks he is in love with Bella. Rachel...
4,13728094,Sam: hey overheard rick say something\r\nSam:...,"Sam is confused, because he overheard Rick com..."

In [12]:
val_data.head()

,id,dialogue,summary
0,13817023,"A: Hi Tom, are you busy tomorrow’s afternoon?\...",A will go to the animal shelter tomorrow to ge...
1,13716628,Emma: I’ve just fallen in love with this adven...,Emma and Rob love the advent calendar. Lauren ...
2,13829420,Jackie: Madison is pregnant\r\nJackie: but she...,Madison is pregnant but she doesn't want to ta...
3,13819648,Marla: <file_photo>\r\nMarla: look what I foun...,Marla found a pair of boxers under her bed.
4,13728448,Robert: Hey give me the address of this music ...,Robert wants Fred to send him the address of t...

In [13]:
train_data["dialogue"][0]

"Amanda: I baked  cookies. Do you want some?\r\nJerry: Sure!\r\nAmanda: I'll bring you tomorrow :-)"

In [15]:
train_data.sample(10)

,id,dialogue,summary
9617,13830024,"Claire: Heeyyy!!\r\nClaire: I have arrived, wa...",Claire and Lucy are meeting at Costa in 2 minu...
2997,13828354,Mary: do you wanna go to see Muse?\r\nTom: yea...,Mary will order the tickets to a Muse concert ...
7478,13680538,Martin: <file_photo>\r\nMartin: these are thos...,Martin wants to buy $300 + shipping shoes. Pau...
3970,13716190,Austin: <file_photo> First attempt with the sl...,Austin made his first slow cooker dish. Ruth a...
2485,13821511,Amy: Could one of you take care of Peter for a...,Amy has to go to work and she needs someone to...
11085,13814141,Isabella: I bought us train tickets on Sunday ...,Isabella bought train tickets for Sunday. Liam...
6254,13821512,Gina: <file_photo>\r\nGina: pancakes with mapl...,Gina has made pancakes with maple syrup hersel...
5841,13810678,"Michael: Hey honey, would you mind taking our ...","Therese will take the dog to the vet, as Miche..."
4232,13816959,Andy: hey man need some help?\r\nSam: no thank...,Sam will let Andy know if he needs some help.
11970,13611843,James: hey lennon the washing machine is fucke...,The washing machine is down. James will text m...

In [16]:
train_data.shape

(14732, 3)

In [17]:
val_data.shape

(818, 3)

## Random Sampeling:

In [18]:
train_data = train_data.sample(
    n = 4000,
    random_state = 42
).reset_index(drop = True)

val_data = val_data.sample(
    n = 500,
    random_state = 42
).reset_index(drop = True)

In [20]:
train_data.shape

(4000, 3)

In [21]:
val_data.shape

(500, 3)

## Data Preprocessing: Cleaning Data

In [24]:
def clean_data(text):
    text = re.sub(r"\r\n", " ", text) # lines
    text = re.sub(r"\s+", " ", text) # spaces
    text = re.sub(r"\<.*?>", " ", text) # html tags
    text = text.strip().lower()
    return text

In [27]:
train_data["dialogue"] = train_data["dialogue"].apply(clean_data)
train_data["summary"] = train_data["summary"].apply(clean_data)

val_data["dialogue"] = val_data["dialogue"].apply(clean_data)
val_data["summary"] = val_data["summary"].apply(clean_data)

In [28]:
train_data["dialogue"][0]

"violet: hi! i came across this austin's article and i thought that you might find it interesting violet: claire: hi! :) thanks, but i've already read it. :) claire: but thanks for thinking about me :)"